module.exports = {
  plugins: [require("@tailwindcss/custom-forms")],
  theme: {
    extend: {
      colors: {
        balance: {
          alert: "#F25042",
          success: "#80E055",
          info: "#56CCF2",
          darkprimary: "#CFDC4F",
          lightprimary: "#E8F18F",
          darkbg: "#50442E",
          lightbg: "#8C7851",
          darkgrey: "#E2E1E1",
          lightgrey: "#F1EDEB",
          lilac: "#EDD3F8",
          DEFAULT: "#121428",
        },
        "pastel-light": {
          alert: "#f07e7e",
          success: "#7edebc",
          fawn: "#fefde8",
          hover: "#92e8f8",
          DEFAULT: "#4b5873",
        },
        "pastel-dark": {
          alert: "#cb5c5c",
          success: "#5caf8c",
          fawn: "#f8f4bc",
          hover: "#6bbcde",
          DEFAULT: "#374054",
        },
        balanced: {
          alert: "#F25042",
          success: "#80E055",
          darkprimary: "#CFDC4F",
          lightprimary: "#E8F18F",
          darkbg: "#50442E",
          lightbg: "#8C7851",
          darkgrey: "#E2E1E1",
          lightgrey: "#F1EDEB",
          lilac: "#EDD3F8",
          DEFAULT: "#121428",
        },
      },
    },
  },
  variants: {},
  plugins: [],
};
